Model created, config:
{'name': 'tf_efficientnetv2_l', 'backbone_name': 'tf_efficientnetv2_l', 'backbone_args': {'drop_path_rate': 0.2}, 'backbone_indices': None, 'image_size': [512, 512], 'num_classes': 2, 'min_level': 3, 'max_level': 7, 'num_levels': 5, 'num_scales': 3, 'aspect_ratios': [[1.0, 1.0], [1.4, 0.7], [0.7, 1.4]], 'anchor_scale': 4.0, 'pad_type': 'same', 'act_type': 'swish', 'norm_layer': None, 'norm_kwargs': {'eps': 0.001, 'momentum': 0.01}, 'box_class_repeats': 3, 'fpn_cell_repeats': 3, 'fpn_channels': 88, 'separable_conv': True, 'apply_resample_bn': True, 'conv_bn_relu_pattern': False, 'downsample_type': 'max', 'upsample_type': 'nearest', 'redundant_bias': True, 'head_bn_level_first': False, 'head_act_type': None, 'fpn_name': None, 'fpn_config': None, 'fpn_drop_path_rate': 0.0, 'alpha': 0.25, 'gamma': 1.5, 'label_smoothing': 0.0, 'legacy_focal': False, 'jit_loss': False, 'delta': 0.1, 'box_loss_weight': 50.0, 'soft_nms': False, 'max_detection_points': 5000, 'max_det_per_image': 100, 'url': ''}
Sanity Checking: 0it [00:00, ?it/s]
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
  | Name  | Type          | Params
----------------------------------------
0 | model | DetBenchTrain | 116 M
----------------------------------------
116 M     Trainable params
0         Non-trainable params
116 M     Total params
467.622   Total estimated model params size (MB)
/Users/mt361/Desktop/COVID_CV/COVID-Classification/venv/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py:48: UserWarning: Detected KeyboardInterrupt, attempting graceful shutdown...
  rank_zero_warn("Detected KeyboardInterrupt, attempting graceful shutdown...")
Error in sys.excepthook:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 319, in decode
    def decode(self, input, final=False):
  File "/Users/mt361/Desktop/COVID_CV/COVID-Classification/venv/lib/python3.9/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 63196) is killed by signal: Interrupt: 2.
Original exception was:
Traceback (most recent call last):
  File "/Users/mt361/Desktop/COVID_CV/COVID-Classification/run.py", line 40, in <module>
    train_save(config, args.wandb)
  File "/Users/mt361/Desktop/COVID_CV/COVID-Classification/run.py", line 28, in train_save
    torch.save(model.state_dict(), f"trained/EfficientDet/{config['backbone']}")
  File "/Users/mt361/Desktop/COVID_CV/COVID-Classification/venv/lib/python3.9/site-packages/torch/serialization.py", line 423, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/Users/mt361/Desktop/COVID_CV/COVID-Classification/venv/lib/python3.9/site-packages/torch/serialization.py", line 635, in _save
    pickler.dump(obj)
  File "/Users/mt361/Desktop/COVID_CV/COVID-Classification/venv/lib/python3.9/site-packages/torch/serialization.py", line 590, in persistent_id
    if isinstance(obj, torch.storage.TypedStorage) or torch.is_storage(obj):
KeyboardInterrupt